### PR TITLE
Add rawhide.spec for building an rpm package

### PR DESCRIPTION
**Pull request by hundertzwei**
Hello,
 with a .spec-file inside the tar.gz it will be easy to build an rpm-package for rpm-based distribuitions.

Good luck!

### CODE REVIEW

**Comment by raforg** [comment]
Hi and Thanks! The license is actually GPLv3+, but I've just looked at https://docs.fedoraproject.org/en-US/legal/license-field/ and it doesn't look as though "GPLv3" or "GPLv3+" is allowed in the License field. It has to contain SPDX identifiers. So it needs to be changed to "GPL-3.0-or-later".

However, there is an additional complication. If you look in the .reuse/dep5 file, which specifies the licensing for REUSE (and for debian packaging), you'll see that one file contains code with a different license that is an old version of the BSD 3 clause license. The wording is slightly different to the official SPDX version of the BSD 3 Clause license, so I had to define it locally in the .reuse/dep5 file with a local LicenseRef- identifier. I don't know if that can be done in the spec file or how (or how to apply it to a single file). Perhaps it doesn't matter. Part of the Fedora licencing documentation (https://docs.fedoraproject.org/en-US/legal/spdx/) mentions leaving out licenses that aren't approved by Fedora (in OR expressions) so maybe it's correct to ignore it. But that URL does mention LicenseRef- identifiers so maybe it is possible. But that old license only applies to part of one source file, not to the application as a whole. And I'm re-releasing the code in that part of that file under GPLv3+ as well. The spec file seems to only refer to the entire program. You know more about it than I do so I'll let you decide what the correct thing to do is. But I suspect that "GPL-3.0-or-later" is sufficient.

Also, please combine the two commits into one. Although I assume I can squash them when accepting the pull request.

And please change the commit message to:

    Add rawhide.spec for building an rpm package

Thanks again!

**Comment by hundertzwei** [comment]
Hello,
 thank you for your answer. I'm to stupid to merge the now 6 (grrr!) commits with this interface. When I tried to squash them on the commandline, I did it on my main branch instead the rpmbuild branch. Please use the "Squash and Merge" option when you merge the pull-request. Thank you!

**Comment by raforg** [comment]
Thanks!

**Comment by raforg** [comment]
I had to add a blank line and do a forced push. I hope that doesn't inconvenience you.

**Pull request merged**
